//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingForHands.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public string NameMaterial { get; set; }
        public Nullable<int> OldCount { get; set; }
        public Nullable<int> NewCount { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
    }
}
