//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingForHands.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialBySupplier = new HashSet<MaterialBySupplier>();
        }
    
        public int Id { get; set; }
        public string NameMaterial { get; set; }
        public int IdTypeMaterial { get; set; }
        public decimal Price { get; set; }
        public int Count { get; set; }
        public int MinCount { get; set; }
        public int CountInBox { get; set; }
        public int TypeDimennsion { get; set; }
        public byte[] Photo { get; set; }
        public string Desctiption { get; set; }
    
        public virtual TypeDimennsion TypeDimennsion1 { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialBySupplier> MaterialBySupplier { get; set; }
    }
}
